runtime bundle/vim-pathogen/autoload/pathogen.vim
execute pathogen#infect()
filetype plugin indent on
colors desert
syntax on

set list!
set listchars=tab:>>,trail:.

set autoindent
set background=dark
set backspace=2
set encoding=utf-8
set expandtab
set history=50
set hlsearch
set nowrap
set number
set ruler
set shiftwidth=4
set showmatch
set showmode
set tabstop=4
set termencoding=utf-8
set textwidth=79

"set statusline+=%#warningmsg#
"set statusline+=%{SyntasticStatuslineFlag()}
"set statusline+=%*
set laststatus=2

"let g:indentLine_setColors=0

let g:syntastic_aggregate_errors=1
let g:syntastic_always_populate_loc_list=1
let g:syntastic_auto_loc_list=0
let g:syntastic_check_on_open=1
let g:syntastic_c_compiler="clang"
let g:syntastic_c_compiler_options="-std=c99 -Wall -Wextra"
let g:syntastic_cpp_compiler="clang++"
let g:syntastic_cpp_compiler_options="-std=c++11 -Wall -Wextra"

let g:ycm_confirm_extra_conf=0
let g:ycm_global_ycm_extra_conf="~/.vim/ycm_extra_conf.py"
"let g:ycm_show_diagnostics_ui=0

if has ("gui_running")
    set guioptions -=T
endif

if has ("gui_macvim")
    set guifont=Menlo:h14
else    
    set guifont=Monospace\ Regular\ 8
endif

