"
" PLUGIN MANAGEMENT
"
runtime bundle/vim-pathogen/autoload/pathogen.vim
execute pathogen#infect()

"
" APPEARANCE
"
set background=dark
colors desert
syntax on
set list!
set listchars=tab:>>,trail:.
"Set vim to assume TrueColor in terminal -- NOT PORTABLE 
"set termguicolors

" Turn off toolbar and menu in {g,mac}vim
if has ("gui_running")
    set guioptions -=T
    set guioptions -=m
endif

" Set fonts in {g,mac}vim
if has ("gui_macvim")
    set guifont=Menlo:h14
else    
    set guifont=Monospace\ Regular\ 8
endif

"
" EDITING
"
filetype plugin indent on
set autoindent
set backspace=2
set encoding=utf-8
set expandtab
set history=50
set hlsearch
set number
set ruler
set shiftwidth=4
set showmatch
set showmode
set tabstop=4
set termencoding=utf-8
set textwidth=79
" Wrapping
set wrap
set textwidth=0 wrapmargin=0
" Spelling (off by default)
set spell spelllang=en_us
set nospell

"
" AIRLINE
"
set laststatus=2

"
" AUTOCLOSE
"
"https://github.com/Valloric/YouCompleteMe/issues/896
let g:AutoClosePumvisible = {"ENTER": "<C-Y>", "ESC": "<ESC>"}

"
" SYNTASTIC
"
"set statusline+=%#warningmsg#
"set statusline+=%{SyntasticStatuslineFlag()}
"set statusline+=%*
let g:syntastic_aggregate_errors=1
let g:syntastic_always_populate_loc_list=1
let g:syntastic_auto_loc_list=0
let g:syntastic_check_on_open=1
let g:syntastic_c_compiler="clang"
let g:syntastic_c_compiler_options="-std=c99 -Wall -Wextra"
let g:syntastic_cpp_compiler="clang++"
let g:syntastic_cpp_compiler_options="-std=c++11 -Wall -Wextra"

"
" YOUCOMPLETEME
"
let g:ycm_confirm_extra_conf=0
let g:ycm_global_ycm_extra_conf="~/.vim/ycm_extra_conf.py"
"let g:ycm_show_diagnostics_ui=0


